# # Copyright (c) 2023, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clausescope: raw
#
# Proposes substitutions for commonly misspelled product names
#
extends: substitution
message: "Use '%s' instead of '%s'."
level: error
ignorecase: false
action:
  name: replace
swap:
  'ACM': API Community Manager
  'APM': Partner Manager
  'ARM': Runtime Manager
  'DW': DataWeave
  'RPA Manger': RPA Manager
  'RTM': Runtime Manager
  'RTF': Runtime Fabric
  'AnyPoint': Anypoint
  'Anypoint platform': Anypoint Platform
  'Cloudhub': CloudHub
  'Cloud Hub': CloudHub
  'Datagraph': DataGraph
  'Data Graph': DataGraph
  'Data graph': DataGraph
  'Dataweave': DataWeave
  'GovCloud': MuleSoft Government Cloud
  'Gov Cloud': MuleSoft Government Cloud
  'Mulesoft': MuleSoft
  'Munit': MUnit
  'Object Store V2': Object Store v2