name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'Mulesoft.zip'
        path: 'Mulesoft'
    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        artifacts: mulesoft.zip
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release to latest
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: latest
        artifacts: Mulesoft.zip
        token: ${{ secrets.GITHUB_TOKEN }}
