on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'mulesoft.zip'
        path: 'mulesoft'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "mulesoft.zip"
        token: ${{ secrets.GITHUB_TOKEN }}