name: Bump version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Zip Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'mulesoft.zip'
        path: 'mulesoft'
        append_to_pre_release_tag: ''
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        artifacts: "mulesoft.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
